
X      X
X      X
X      X
X      X
X      X
  XXX
            
X      X
XX    X
X  X  X
X    XX
X      X
            
XXXX  
X      X
X      X
X      X
X      X
XXXX  
            
X      X
X      X
X      X
X      X
X      X
  XXX  
            
XXXXX
    X    
    X    
    X    
    X    
    X    
              
    XX
  X    
  X    
XX    
  X    
  X    
  X    
    XX
            
X      X
X      X
X      X
X      X
X      X
  XXX  
            
XXXX  
X      X
X      X
XXXX  
X          
X          
              
              
              
              
              
              
              
XXXXX
            
XXXX  
X      X
X      X
X      X
X      X
XXXX  

  XXX  
X      X
X      X
X      X
X      X
  XXX  
            
X      X
X      X
X      X
X  X  X
XX  XX
X      X
            
X      X
XX    X
X  X  X
X    XX
X      X
              
              
              
              
              
              
              
XXXXXXX
            
  XXX  
X      X
X        
X    XX
X      X
  XXX  
        
X
X
X
X
X
X
            
XXXX  
X      X
X      X
XXXX  
X    X  
X      X
            
XXXX  
X      X
X      X
XXXX  
X    X  
X      X
            
X          
X          
X          
X          
X          
XXXXX
            
X          
X          
X          
X          
X          
XXXXX
            
XX    
    X    
    X    
    XX  
    X    
    X    
    X    
XX    

