ENCODERS = {
    0: "None",
    1: "AES256",
    2: "AES128"
}

TLV_PACKET_TYPES = {
    0: "REQ",
    1: "RESP"
}

TLV_META_TYPE_NONE         = 0
TLV_META_TYPE_STRING       = (1 << 16)
TLV_META_TYPE_UINT         = (1 << 17)
TLV_META_TYPE_RAW          = (1 << 18)
TLV_META_TYPE_BOOL         = (1 << 19)
TLV_META_TYPE_QWORD        = (1 << 20)
TLV_META_TYPE_COMPRESSED   = (1 << 29)
TLV_META_TYPE_GROUP        = (1 << 30)
TLV_META_TYPE_COMPLEX      = (1 << 31)

tlv_types = {
    (TLV_META_TYPE_NONE    | 0): "TLV_TYPE_ANY",
    (TLV_META_TYPE_UINT    | 1): "TLV_TYPE_COMMAND_ID",
    (TLV_META_TYPE_STRING  | 2): "TLV_TYPE_REQUEST_ID",
    (TLV_META_TYPE_GROUP   | 3): "TLV_TYPE_EXCEPTION",
    (TLV_META_TYPE_UINT    | 4): "TLV_TYPE_RESULT",
    (TLV_META_TYPE_STRING  | 10): "TLV_TYPE_STRING",
    (TLV_META_TYPE_UINT    | 11): "TLV_TYPE_UINT",
    (TLV_META_TYPE_BOOL    | 12): "TLV_TYPE_BOOL",
    (TLV_META_TYPE_UINT    | 25): "TLV_TYPE_LENGTH",
    (TLV_META_TYPE_RAW     | 26): "TLV_TYPE_DATA",
    (TLV_META_TYPE_UINT    | 27): "TLV_TYPE_FLAGS",
    (TLV_META_TYPE_UINT    | 50): "TLV_TYPE_CHANNEL_ID",
    (TLV_META_TYPE_STRING  | 51): "TLV_TYPE_CHANNEL_TYPE",
    (TLV_META_TYPE_RAW     | 52): "TLV_TYPE_CHANNEL_DATA",
    (TLV_META_TYPE_GROUP   | 53): "TLV_TYPE_CHANNEL_DATA_GROUP",
    (TLV_META_TYPE_UINT    | 54): "TLV_TYPE_CHANNEL_CLASS",
    (TLV_META_TYPE_UINT    | 55): "TLV_TYPE_CHANNEL_PARENTID",
    (TLV_META_TYPE_UINT    | 70): "TLV_TYPE_SEEK_WHENCE",
    (TLV_META_TYPE_UINT    | 71): "TLV_TYPE_SEEK_OFFSET",
    (TLV_META_TYPE_UINT    | 72): "TLV_TYPE_SEEK_POS",
    (TLV_META_TYPE_UINT    | 300): "TLV_TYPE_EXCEPTION_CODE",
    (TLV_META_TYPE_STRING  | 301): "TLV_TYPE_EXCEPTION_STRING",
    (TLV_META_TYPE_STRING  | 400): "TLV_TYPE_LIBRARY_PATH",
    (TLV_META_TYPE_STRING  | 401): "TLV_TYPE_TARGET_PATH",
    (TLV_META_TYPE_UINT    | 402): "TLV_TYPE_MIGRATE_PID",
    (TLV_META_TYPE_UINT    | 403): "TLV_TYPE_MIGRATE_LEN",
    (TLV_META_TYPE_UINT    | 430): "TLV_TYPE_TRANS_TYPE",
    (TLV_META_TYPE_STRING  | 431): "TLV_TYPE_TRANS_URL",
    (TLV_META_TYPE_STRING  | 432): "TLV_TYPE_TRANS_UA",
    (TLV_META_TYPE_UINT    | 433): "TLV_TYPE_TRANS_COMM_TIMEOUT",
    (TLV_META_TYPE_UINT    | 434): "TLV_TYPE_TRANS_SESSION_EXP",
    (TLV_META_TYPE_RAW     | 435): "TLV_TYPE_TRANS_CERT_HASH",
    (TLV_META_TYPE_STRING  | 436): "TLV_TYPE_TRANS_PROXY_HOST",
    (TLV_META_TYPE_STRING  | 437): "TLV_TYPE_TRANS_PROXY_USER",
    (TLV_META_TYPE_STRING  | 438): "TLV_TYPE_TRANS_PROXY_PASS",
    (TLV_META_TYPE_UINT    | 439): "TLV_TYPE_TRANS_RETRY_TOTAL",
    (TLV_META_TYPE_UINT    | 440): "TLV_TYPE_TRANS_RETRY_WAIT",
    (TLV_META_TYPE_GROUP   | 441): "TLV_TYPE_TRANS_GROUP",
    (TLV_META_TYPE_STRING  | 460): "TLV_TYPE_MACHINE_ID",
    (TLV_META_TYPE_RAW     | 461): "TLV_TYPE_UUID",
    (TLV_META_TYPE_RAW     | 462): "TLV_TYPE_SESSION_GUID",
    (TLV_META_TYPE_RAW     | 550): "TLV_TYPE_RSA_PUB_KEY",
    (TLV_META_TYPE_UINT    | 551): "TLV_TYPE_SYM_KEY_TYPE",
    (TLV_META_TYPE_RAW     | 552): "TLV_TYPE_SYM_KEY",
    (TLV_META_TYPE_RAW     | 553): "TLV_TYPE_ENC_SYM_KEY",
    (TLV_META_TYPE_QWORD   | 600): "TLV_TYPE_HANDLE",
    (TLV_META_TYPE_BOOL    | 601): "TLV_TYPE_INHERIT",
    (TLV_META_TYPE_QWORD   | 630): "TLV_TYPE_PROCESS_HANDLE",
    (TLV_META_TYPE_QWORD   | 631): "TLV_TYPE_THREAD_HANDLE",
    (TLV_META_TYPE_STRING  | 1200): "TLV_TYPE_DIRECTORY_PATH",
    (TLV_META_TYPE_STRING  | 1201): "TLV_TYPE_FILE_NAME",
    (TLV_META_TYPE_STRING  | 1202): "TLV_TYPE_FILE_PATH",
    (TLV_META_TYPE_STRING  | 1203): "TLV_TYPE_FILE_MODE",
    (TLV_META_TYPE_UINT    | 1204): "TLV_TYPE_FILE_SIZE",
    (TLV_META_TYPE_RAW     | 1206): "TLV_TYPE_FILE_HASH",
    (TLV_META_TYPE_COMPLEX | 1221): "TLV_TYPE_STAT_BUF",
    (TLV_META_TYPE_BOOL    | 1230): "TLV_TYPE_SEARCH_RECURSE",
    (TLV_META_TYPE_STRING  | 1231): "TLV_TYPE_SEARCH_GLOB",
    (TLV_META_TYPE_STRING  | 1232): "TLV_TYPE_SEARCH_ROOT",
    (TLV_META_TYPE_GROUP   | 1233): "TLV_TYPE_SEARCH_RESULTS",
    (TLV_META_TYPE_UINT    | 1234): "TLV_TYPE_FILE_MODE_T",
    (TLV_META_TYPE_UINT    | 1235): "TLV_TYPE_SEARCH_MTIME",
    (TLV_META_TYPE_UINT    | 1236): "TLV_TYPE_SEARCH_M_START_DATE",
    (TLV_META_TYPE_UINT    | 1237): "TLV_TYPE_SEARCH_M_END_DATE",
    (TLV_META_TYPE_STRING  | 1400): "TLV_TYPE_HOST_NAME",
    (TLV_META_TYPE_UINT    | 1401): "TLV_TYPE_PORT",
    (TLV_META_TYPE_UINT    | 1402): "TLV_TYPE_INTERFACE_MTU",
    (TLV_META_TYPE_STRING  | 1403): "TLV_TYPE_INTERFACE_FLAGS",
    (TLV_META_TYPE_UINT    | 1404): "TLV_TYPE_INTERFACE_INDEX",
    (TLV_META_TYPE_RAW     | 1420): "TLV_TYPE_SUBNET",
    (TLV_META_TYPE_RAW     | 1421): "TLV_TYPE_NETMASK",
    (TLV_META_TYPE_RAW     | 1422): "TLV_TYPE_GATEWAY",
    (TLV_META_TYPE_GROUP   | 1423): "TLV_TYPE_NETWORK_ROUTE",
    (TLV_META_TYPE_UINT    | 1424): "TLV_TYPE_IP_PREFIX",
    (TLV_META_TYPE_GROUP   | 1425): "TLV_TYPE_ARP_ENTRY",
    (TLV_META_TYPE_RAW     | 1430): "TLV_TYPE_IP",
    (TLV_META_TYPE_RAW     | 1431): "TLV_TYPE_MAC_ADDRESS",
    (TLV_META_TYPE_STRING  | 1432): "TLV_TYPE_MAC_NAME",
    (TLV_META_TYPE_GROUP   | 1433): "TLV_TYPE_NETWORK_INTERFACE",
    (TLV_META_TYPE_RAW     | 1434): "TLV_TYPE_IP6_SCOPE",
    (TLV_META_TYPE_STRING  | 1440): "TLV_TYPE_SUBNET_STRING",
    (TLV_META_TYPE_STRING  | 1441): "TLV_TYPE_NETMASK_STRING",
    (TLV_META_TYPE_STRING  | 1442): "TLV_TYPE_GATEWAY_STRING",
    (TLV_META_TYPE_UINT    | 1443): "TLV_TYPE_ROUTE_METRIC",
    (TLV_META_TYPE_UINT    | 1444): "TLV_TYPE_ADDR_TYPE",
    (TLV_META_TYPE_BOOL  | 1445): "TLV_TYPE_PROXY_CFG_AUTODETECT",
    (TLV_META_TYPE_STRING| 1446): "TLV_TYPE_PROXY_CFG_AUTOCONFIGURL",
    (TLV_META_TYPE_STRING| 1447): "TLV_TYPE_PROXY_CFG_PROXY",
    (TLV_META_TYPE_STRING| 1448): "TLV_TYPE_PROXY_CFG_PROXYBYPASS",
    (TLV_META_TYPE_STRING  | 1500): "TLV_TYPE_PEER_HOST",
    (TLV_META_TYPE_UINT    | 1501): "TLV_TYPE_PEER_PORT",
    (TLV_META_TYPE_STRING  | 1502): "TLV_TYPE_LOCAL_HOST",
    (TLV_META_TYPE_UINT    | 1503): "TLV_TYPE_LOCAL_PORT",
    (TLV_META_TYPE_UINT    | 1504): "TLV_TYPE_CONNECT_RETRIES",
    (TLV_META_TYPE_GROUP   | 1505): "TLV_TYPE_NETSTAT_ENTRY",
    (TLV_META_TYPE_RAW     | 1506): "TLV_TYPE_PEER_HOST_RAW",
    (TLV_META_TYPE_RAW     | 1507): "TLV_TYPE_LOCAL_HOST_RAW",
    (TLV_META_TYPE_UINT    | 1530): "TLV_TYPE_SHUTDOWN_HOW",
    (TLV_META_TYPE_QWORD   | 1000): "TLV_TYPE_HKEY",
    #(TLV_TYPE_HKEY): "TLV_TYPE_ROOT_KEY",
    (TLV_META_TYPE_STRING  | 1001): "TLV_TYPE_BASE_KEY",
    (TLV_META_TYPE_UINT    | 1002): "TLV_TYPE_PERMISSION",
    (TLV_META_TYPE_STRING  | 1003): "TLV_TYPE_KEY_NAME",
    (TLV_META_TYPE_STRING  | 1010): "TLV_TYPE_VALUE_NAME",
    (TLV_META_TYPE_UINT    | 1011): "TLV_TYPE_VALUE_TYPE",
    (TLV_META_TYPE_RAW     | 1012): "TLV_TYPE_VALUE_DATA",
    (TLV_META_TYPE_STRING  | 1013): "TLV_TYPE_TARGET_HOST",
    (TLV_META_TYPE_STRING  | 1040): "TLV_TYPE_COMPUTER_NAME",
    (TLV_META_TYPE_STRING  | 1041): "TLV_TYPE_OS_NAME",
    (TLV_META_TYPE_STRING  | 1042): "TLV_TYPE_USER_NAME",
    (TLV_META_TYPE_STRING  | 1043): "TLV_TYPE_ARCHITECTURE",
    (TLV_META_TYPE_STRING  | 1045): "TLV_TYPE_SID",
    (TLV_META_TYPE_STRING  | 1048): "TLV_TYPE_LOCAL_DATETIME",
    (TLV_META_TYPE_STRING  | 1049): "TLV_TYPE_BUILD_TUPLE",
    (TLV_META_TYPE_STRING  | 1100): "TLV_TYPE_ENV_VARIABLE",
    (TLV_META_TYPE_STRING  | 1101): "TLV_TYPE_ENV_VALUE",
    (TLV_META_TYPE_GROUP   | 1102): "TLV_TYPE_ENV_GROUP",
    #(1 << 0): "DELETE_KEY_FLAG_RECURSIVE",
    (TLV_META_TYPE_QWORD   | 2000): "TLV_TYPE_BASE_ADDRESS",
    (TLV_META_TYPE_UINT    | 2001): "TLV_TYPE_ALLOCATION_TYPE",
    (TLV_META_TYPE_UINT    | 2002): "TLV_TYPE_PROTECTION",
    (TLV_META_TYPE_UINT    | 2003): "TLV_TYPE_PROCESS_PERMS",
    (TLV_META_TYPE_RAW     | 2004): "TLV_TYPE_PROCESS_MEMORY",
    (TLV_META_TYPE_QWORD   | 2005): "TLV_TYPE_ALLOC_BASE_ADDRESS",
    (TLV_META_TYPE_UINT    | 2006): "TLV_TYPE_MEMORY_STATE",
    (TLV_META_TYPE_UINT    | 2007): "TLV_TYPE_MEMORY_TYPE",
    (TLV_META_TYPE_UINT    | 2008): "TLV_TYPE_ALLOC_PROTECTION",
    (TLV_META_TYPE_UINT    | 2300): "TLV_TYPE_PID",
    (TLV_META_TYPE_STRING  | 2301): "TLV_TYPE_PROCESS_NAME",
    (TLV_META_TYPE_STRING  | 2302): "TLV_TYPE_PROCESS_PATH",
    (TLV_META_TYPE_GROUP   | 2303): "TLV_TYPE_PROCESS_GROUP",
    (TLV_META_TYPE_UINT    | 2304): "TLV_TYPE_PROCESS_FLAGS",
    (TLV_META_TYPE_STRING  | 2305): "TLV_TYPE_PROCESS_ARGUMENTS",
    (TLV_META_TYPE_UINT    | 2306): "TLV_TYPE_PROCESS_ARCH",
    (TLV_META_TYPE_UINT    | 2307): "TLV_TYPE_PARENT_PID",
    (TLV_META_TYPE_STRING  | 2309): "TLV_TYPE_PROCESS_ARCH_NAME",
    (TLV_META_TYPE_STRING  | 2400): "TLV_TYPE_IMAGE_FILE",
    (TLV_META_TYPE_STRING  | 2401): "TLV_TYPE_IMAGE_FILE_PATH",
    (TLV_META_TYPE_STRING  | 2402): "TLV_TYPE_PROCEDURE_NAME",
    (TLV_META_TYPE_QWORD   | 2403): "TLV_TYPE_PROCEDURE_ADDRESS",
    (TLV_META_TYPE_QWORD   | 2404): "TLV_TYPE_IMAGE_BASE",
    (TLV_META_TYPE_GROUP   | 2405): "TLV_TYPE_IMAGE_GROUP",
    (TLV_META_TYPE_STRING  | 2406): "TLV_TYPE_IMAGE_NAME",
    (TLV_META_TYPE_UINT    | 2500): "TLV_TYPE_THREAD_ID",
    (TLV_META_TYPE_UINT    | 2502): "TLV_TYPE_THREAD_PERMS",
    (TLV_META_TYPE_UINT    | 2510): "TLV_TYPE_EXIT_CODE",
    (TLV_META_TYPE_QWORD   | 2511): "TLV_TYPE_ENTRY_POINT",
    (TLV_META_TYPE_QWORD   | 2512): "TLV_TYPE_ENTRY_PARAMETER",
    (TLV_META_TYPE_UINT    | 2513): "TLV_TYPE_CREATION_FLAGS",
    (TLV_META_TYPE_STRING  | 2540): "TLV_TYPE_REGISTER_NAME",
    (TLV_META_TYPE_UINT    | 2541): "TLV_TYPE_REGISTER_SIZE",
    (TLV_META_TYPE_UINT    | 2542): "TLV_TYPE_REGISTER_VALUE_32",
    (TLV_META_TYPE_GROUP   | 2550): "TLV_TYPE_REGISTER",
    (TLV_META_TYPE_UINT    | 2600): "TLV_TYPE_TERMINAL_ROWS",
    (TLV_META_TYPE_UINT    | 2601): "TLV_TYPE_TERMINAL_COLUMNS",
    (TLV_META_TYPE_STRING   | 2650): "TLV_TYPE_MEMORY_SEARCH_NEEDLE",
    (TLV_META_TYPE_GROUP    | 2651): "TLV_TYPE_MEMORY_SEARCH_RESULTS",
    (TLV_META_TYPE_UINT     | 2652): "TLV_TYPE_MEMORY_SEARCH_MATCH_LEN",
    (TLV_META_TYPE_QWORD    | 2653): "TLV_TYPE_MEMORY_SEARCH_START_ADDR",
    (TLV_META_TYPE_QWORD    | 2654): "TLV_TYPE_MEMORY_SEARCH_SECT_LEN",
    (TLV_META_TYPE_QWORD    | 2655): "TLV_TYPE_MEMORY_SEARCH_MATCH_ADDR",
    (TLV_META_TYPE_STRING   | 2656): "TLV_TYPE_MEMORY_SEARCH_MATCH_STR",
    (TLV_META_TYPE_UINT    | 3000): "TLV_TYPE_IDLE_TIME",
    (TLV_META_TYPE_STRING  | 3001): "TLV_TYPE_KEYS_DUMP",
    (TLV_META_TYPE_STRING  | 3002): "TLV_TYPE_DESKTOP",
    (TLV_META_TYPE_RAW  | 3002): "TLV_TYPE_DESKTOP_SCREENSHOT",
    (TLV_META_TYPE_UINT | 3008): "TLV_TYPE_DESKTOP_SCREENSHOT_QUALITY",
    (TLV_META_TYPE_STRING  | 3014): "TLV_TYPE_KEYS_SEND",
    (TLV_META_TYPE_UINT    | 3015): "TLV_TYPE_MOUSE_ACTION",
    (TLV_META_TYPE_UINT    | 3016): "TLV_TYPE_MOUSE_X",
    (TLV_META_TYPE_UINT    | 3017): "TLV_TYPE_MOUSE_Y",
    (TLV_META_TYPE_RAW     | 3018): "TLV_TYPE_KEYEVENT_SEND",
    (TLV_META_TYPE_STRING  | 4000): "TLV_TYPE_EVENT_SOURCENAME",
    (TLV_META_TYPE_QWORD   | 4001): "TLV_TYPE_EVENT_HANDLE",
    (TLV_META_TYPE_UINT    | 4002): "TLV_TYPE_EVENT_NUMRECORDS",
    (TLV_META_TYPE_UINT    | 4003): "TLV_TYPE_EVENT_READFLAGS",
    (TLV_META_TYPE_UINT    | 4004): "TLV_TYPE_EVENT_RECORDOFFSET",
    (TLV_META_TYPE_UINT    | 4006): "TLV_TYPE_EVENT_RECORDNUMBER",
    (TLV_META_TYPE_UINT    | 4007): "TLV_TYPE_EVENT_TIMEGENERATED",
    (TLV_META_TYPE_UINT    | 4008): "TLV_TYPE_EVENT_TIMEWRITTEN",
    (TLV_META_TYPE_UINT    | 4009): "TLV_TYPE_EVENT_ID",
    (TLV_META_TYPE_UINT    | 4010): "TLV_TYPE_EVENT_TYPE",
    (TLV_META_TYPE_UINT    | 4011): "TLV_TYPE_EVENT_CATEGORY",
    (TLV_META_TYPE_STRING  | 4012): "TLV_TYPE_EVENT_STRING",
    (TLV_META_TYPE_RAW     | 4013): "TLV_TYPE_EVENT_DATA",
    (TLV_META_TYPE_UINT    | 4100): "TLV_TYPE_POWER_FLAGS",
    (TLV_META_TYPE_UINT    | 4101): "TLV_TYPE_POWER_REASON"
}

cmd_ids = {}
cmd_ids[0] = "EXTENSION_ID_CORE"
cmd_ids[1000] = "EXTENSION_ID_STDAPI"
cmd_ids[2000] = "EXTENSION_ID_PRIV"
cmd_ids[3000] = "EXTENSION_ID_EXTAPI"
cmd_ids[4000] = "EXTENSION_ID_SNIFFER"
cmd_ids[7000] = "EXTENSION_ID_WINPMEM"
cmd_ids[8000] = "EXTENSION_ID_KIWI"
cmd_ids[10000] = "EXTENSION_ID_UNHOOK"
cmd_ids[11000] = "EXTENSION_ID_ESPIA"
cmd_ids[12000] = "EXTENSION_ID_INCOGNITO"
cmd_ids[13000] = "EXTENSION_ID_PYTHON"
cmd_ids[14000] = "EXTENSION_ID_POWERSHELL"
cmd_ids[15000] = "EXTENSION_ID_LANATTACKS"
cmd_ids[16000] = "EXTENSION_ID_PEINJECTOR"
cmd_ids[17000] = "EXTENSION_ID_MIMIKATZ"
cmd_ids[1] = "COMMAND_ID_CORE_CHANNEL_CLOSE"
cmd_ids[2] = "COMMAND_ID_CORE_CHANNEL_EOF"
cmd_ids[3] = "COMMAND_ID_CORE_CHANNEL_INTERACT"
cmd_ids[4] = "COMMAND_ID_CORE_CHANNEL_OPEN"
cmd_ids[5] = "COMMAND_ID_CORE_CHANNEL_READ"
cmd_ids[6] = "COMMAND_ID_CORE_CHANNEL_SEEK"
cmd_ids[7] = "COMMAND_ID_CORE_CHANNEL_TELL"
cmd_ids[8] = "COMMAND_ID_CORE_CHANNEL_WRITE"
cmd_ids[9] = "COMMAND_ID_CORE_CONSOLE_WRITE"
cmd_ids[10] = "COMMAND_ID_CORE_ENUMEXTCMD"
cmd_ids[11] = "COMMAND_ID_CORE_GET_SESSION_GUID"
cmd_ids[12] = "COMMAND_ID_CORE_LOADLIB"
cmd_ids[13] = "COMMAND_ID_CORE_MACHINE_ID"
cmd_ids[14] = "COMMAND_ID_CORE_MIGRATE"
cmd_ids[15] = "COMMAND_ID_CORE_NATIVE_ARCH"
cmd_ids[16] = "COMMAND_ID_CORE_NEGOTIATE_TLV_ENCRYPTION"
cmd_ids[17] = "COMMAND_ID_CORE_PATCH_URL"
cmd_ids[18] = "COMMAND_ID_CORE_PIVOT_ADD"
cmd_ids[19] = "COMMAND_ID_CORE_PIVOT_REMOVE"
cmd_ids[20] = "COMMAND_ID_CORE_PIVOT_SESSION_DIED"
cmd_ids[21] = "COMMAND_ID_CORE_SET_SESSION_GUID"
cmd_ids[22] = "COMMAND_ID_CORE_SET_UUID"
cmd_ids[23] = "COMMAND_ID_CORE_SHUTDOWN"
cmd_ids[24] = "COMMAND_ID_CORE_TRANSPORT_ADD"
cmd_ids[25] = "COMMAND_ID_CORE_TRANSPORT_CHANGE"
cmd_ids[26] = "COMMAND_ID_CORE_TRANSPORT_GETCERTHASH"
cmd_ids[27] = "COMMAND_ID_CORE_TRANSPORT_LIST"
cmd_ids[28] = "COMMAND_ID_CORE_TRANSPORT_NEXT"
cmd_ids[29] = "COMMAND_ID_CORE_TRANSPORT_PREV"
cmd_ids[30] = "COMMAND_ID_CORE_TRANSPORT_REMOVE"
cmd_ids[31] = "COMMAND_ID_CORE_TRANSPORT_SETCERTHASH"
cmd_ids[32] = "COMMAND_ID_CORE_TRANSPORT_SET_TIMEOUTS"
cmd_ids[33] = "COMMAND_ID_CORE_TRANSPORT_SLEEP"
cmd_ids[1001] = "COMMAND_ID_STDAPI_FS_CHDIR"
cmd_ids[1002] = "COMMAND_ID_STDAPI_FS_CHMOD"
cmd_ids[1003] = "COMMAND_ID_STDAPI_FS_DELETE_DIR"
cmd_ids[1004] = "COMMAND_ID_STDAPI_FS_DELETE_FILE"
cmd_ids[1005] = "COMMAND_ID_STDAPI_FS_FILE_COPY"
cmd_ids[1006] = "COMMAND_ID_STDAPI_FS_FILE_EXPAND_PATH"
cmd_ids[1007] = "COMMAND_ID_STDAPI_FS_FILE_MOVE"
cmd_ids[1008] = "COMMAND_ID_STDAPI_FS_GETWD"
cmd_ids[1009] = "COMMAND_ID_STDAPI_FS_LS"
cmd_ids[1010] = "COMMAND_ID_STDAPI_FS_MD5"
cmd_ids[1011] = "COMMAND_ID_STDAPI_FS_MKDIR"
cmd_ids[1012] = "COMMAND_ID_STDAPI_FS_MOUNT_SHOW"
cmd_ids[1013] = "COMMAND_ID_STDAPI_FS_SEARCH"
cmd_ids[1014] = "COMMAND_ID_STDAPI_FS_SEPARATOR"
cmd_ids[1015] = "COMMAND_ID_STDAPI_FS_SHA1"
cmd_ids[1016] = "COMMAND_ID_STDAPI_FS_STAT"
cmd_ids[1017] = "COMMAND_ID_STDAPI_NET_CONFIG_ADD_ROUTE"
cmd_ids[1018] = "COMMAND_ID_STDAPI_NET_CONFIG_GET_ARP_TABLE"
cmd_ids[1019] = "COMMAND_ID_STDAPI_NET_CONFIG_GET_INTERFACES"
cmd_ids[1020] = "COMMAND_ID_STDAPI_NET_CONFIG_GET_NETSTAT"
cmd_ids[1021] = "COMMAND_ID_STDAPI_NET_CONFIG_GET_PROXY"
cmd_ids[1022] = "COMMAND_ID_STDAPI_NET_CONFIG_GET_ROUTES"
cmd_ids[1023] = "COMMAND_ID_STDAPI_NET_CONFIG_REMOVE_ROUTE"
cmd_ids[1024] = "COMMAND_ID_STDAPI_NET_RESOLVE_HOST"
cmd_ids[1025] = "COMMAND_ID_STDAPI_NET_RESOLVE_HOSTS"
cmd_ids[1026] = "COMMAND_ID_STDAPI_NET_SOCKET_TCP_SHUTDOWN"
cmd_ids[1027] = "COMMAND_ID_STDAPI_NET_TCP_CHANNEL_OPEN"
cmd_ids[1028] = "COMMAND_ID_STDAPI_RAILGUN_API"
cmd_ids[1029] = "COMMAND_ID_STDAPI_RAILGUN_API_MULTI"
cmd_ids[1030] = "COMMAND_ID_STDAPI_RAILGUN_MEMREAD"
cmd_ids[1031] = "COMMAND_ID_STDAPI_RAILGUN_MEMWRITE"
cmd_ids[1032] = "COMMAND_ID_STDAPI_REGISTRY_CHECK_KEY_EXISTS"
cmd_ids[1033] = "COMMAND_ID_STDAPI_REGISTRY_CLOSE_KEY"
cmd_ids[1034] = "COMMAND_ID_STDAPI_REGISTRY_CREATE_KEY"
cmd_ids[1035] = "COMMAND_ID_STDAPI_REGISTRY_DELETE_KEY"
cmd_ids[1036] = "COMMAND_ID_STDAPI_REGISTRY_DELETE_VALUE"
cmd_ids[1037] = "COMMAND_ID_STDAPI_REGISTRY_ENUM_KEY"
cmd_ids[1038] = "COMMAND_ID_STDAPI_REGISTRY_ENUM_KEY_DIRECT"
cmd_ids[1039] = "COMMAND_ID_STDAPI_REGISTRY_ENUM_VALUE"
cmd_ids[1040] = "COMMAND_ID_STDAPI_REGISTRY_ENUM_VALUE_DIRECT"
cmd_ids[1041] = "COMMAND_ID_STDAPI_REGISTRY_LOAD_KEY"
cmd_ids[1042] = "COMMAND_ID_STDAPI_REGISTRY_OPEN_KEY"
cmd_ids[1043] = "COMMAND_ID_STDAPI_REGISTRY_OPEN_REMOTE_KEY"
cmd_ids[1044] = "COMMAND_ID_STDAPI_REGISTRY_QUERY_CLASS"
cmd_ids[1045] = "COMMAND_ID_STDAPI_REGISTRY_QUERY_VALUE"
cmd_ids[1046] = "COMMAND_ID_STDAPI_REGISTRY_QUERY_VALUE_DIRECT"
cmd_ids[1047] = "COMMAND_ID_STDAPI_REGISTRY_SET_VALUE"
cmd_ids[1048] = "COMMAND_ID_STDAPI_REGISTRY_SET_VALUE_DIRECT"
cmd_ids[1049] = "COMMAND_ID_STDAPI_REGISTRY_UNLOAD_KEY"
cmd_ids[1050] = "COMMAND_ID_STDAPI_SYS_CONFIG_DRIVER_LIST"
cmd_ids[1051] = "COMMAND_ID_STDAPI_SYS_CONFIG_DROP_TOKEN"
cmd_ids[1052] = "COMMAND_ID_STDAPI_SYS_CONFIG_GETENV"
cmd_ids[1053] = "COMMAND_ID_STDAPI_SYS_CONFIG_GETPRIVS"
cmd_ids[1054] = "COMMAND_ID_STDAPI_SYS_CONFIG_GETSID"
cmd_ids[1055] = "COMMAND_ID_STDAPI_SYS_CONFIG_GETUID"
cmd_ids[1056] = "COMMAND_ID_STDAPI_SYS_CONFIG_LOCALTIME"
cmd_ids[1057] = "COMMAND_ID_STDAPI_SYS_CONFIG_REV2SELF"
cmd_ids[1058] = "COMMAND_ID_STDAPI_SYS_CONFIG_STEAL_TOKEN"
cmd_ids[1059] = "COMMAND_ID_STDAPI_SYS_CONFIG_SYSINFO"
cmd_ids[1060] = "COMMAND_ID_STDAPI_SYS_EVENTLOG_CLEAR"
cmd_ids[1061] = "COMMAND_ID_STDAPI_SYS_EVENTLOG_CLOSE"
cmd_ids[1062] = "COMMAND_ID_STDAPI_SYS_EVENTLOG_NUMRECORDS"
cmd_ids[1063] = "COMMAND_ID_STDAPI_SYS_EVENTLOG_OLDEST"
cmd_ids[1064] = "COMMAND_ID_STDAPI_SYS_EVENTLOG_OPEN"
cmd_ids[1065] = "COMMAND_ID_STDAPI_SYS_EVENTLOG_READ"
cmd_ids[1066] = "COMMAND_ID_STDAPI_SYS_POWER_EXITWINDOWS"
cmd_ids[1067] = "COMMAND_ID_STDAPI_SYS_PROCESS_ATTACH"
cmd_ids[1068] = "COMMAND_ID_STDAPI_SYS_PROCESS_CLOSE"
cmd_ids[1069] = "COMMAND_ID_STDAPI_SYS_PROCESS_EXECUTE"
cmd_ids[1070] = "COMMAND_ID_STDAPI_SYS_PROCESS_GET_INFO"
cmd_ids[1071] = "COMMAND_ID_STDAPI_SYS_PROCESS_GET_PROCESSES"
cmd_ids[1072] = "COMMAND_ID_STDAPI_SYS_PROCESS_GETPID"
cmd_ids[1073] = "COMMAND_ID_STDAPI_SYS_PROCESS_IMAGE_GET_IMAGES"
cmd_ids[1074] = "COMMAND_ID_STDAPI_SYS_PROCESS_IMAGE_GET_PROC_ADDRESS"
cmd_ids[1075] = "COMMAND_ID_STDAPI_SYS_PROCESS_IMAGE_LOAD"
cmd_ids[1076] = "COMMAND_ID_STDAPI_SYS_PROCESS_IMAGE_UNLOAD"
cmd_ids[1077] = "COMMAND_ID_STDAPI_SYS_PROCESS_KILL"
cmd_ids[1078] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_ALLOCATE"
cmd_ids[1079] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_FREE"
cmd_ids[1080] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_LOCK"
cmd_ids[1081] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_PROTECT"
cmd_ids[1082] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_QUERY"
cmd_ids[1083] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_READ"
cmd_ids[1084] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_UNLOCK"
cmd_ids[1085] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_WRITE"
cmd_ids[1086] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_CLOSE"
cmd_ids[1087] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_CREATE"
cmd_ids[1088] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_GET_THREADS"
cmd_ids[1089] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_OPEN"
cmd_ids[1090] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_QUERY_REGS"
cmd_ids[1091] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_RESUME"
cmd_ids[1092] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_SET_REGS"
cmd_ids[1093] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_SUSPEND"
cmd_ids[1094] = "COMMAND_ID_STDAPI_SYS_PROCESS_THREAD_TERMINATE"
cmd_ids[1095] = "COMMAND_ID_STDAPI_SYS_PROCESS_WAIT"
cmd_ids[1096] = "COMMAND_ID_STDAPI_UI_DESKTOP_ENUM"
cmd_ids[1097] = "COMMAND_ID_STDAPI_UI_DESKTOP_GET"
cmd_ids[1098] = "COMMAND_ID_STDAPI_UI_DESKTOP_SCREENSHOT"
cmd_ids[1099] = "COMMAND_ID_STDAPI_UI_DESKTOP_SET"
cmd_ids[1100] = "COMMAND_ID_STDAPI_UI_ENABLE_KEYBOARD"
cmd_ids[1101] = "COMMAND_ID_STDAPI_UI_ENABLE_MOUSE"
cmd_ids[1102] = "COMMAND_ID_STDAPI_UI_GET_IDLE_TIME"
cmd_ids[1103] = "COMMAND_ID_STDAPI_UI_GET_KEYS_UTF8"
cmd_ids[1104] = "COMMAND_ID_STDAPI_UI_SEND_KEYEVENT"
cmd_ids[1105] = "COMMAND_ID_STDAPI_UI_SEND_KEYS"
cmd_ids[1106] = "COMMAND_ID_STDAPI_UI_SEND_MOUSE"
cmd_ids[1107] = "COMMAND_ID_STDAPI_UI_START_KEYSCAN"
cmd_ids[1108] = "COMMAND_ID_STDAPI_UI_STOP_KEYSCAN"
cmd_ids[1109] = "COMMAND_ID_STDAPI_UI_UNLOCK_DESKTOP"
cmd_ids[1110] = "COMMAND_ID_STDAPI_WEBCAM_AUDIO_RECORD"
cmd_ids[1111] = "COMMAND_ID_STDAPI_WEBCAM_GET_FRAME"
cmd_ids[1112] = "COMMAND_ID_STDAPI_WEBCAM_LIST"
cmd_ids[1113] = "COMMAND_ID_STDAPI_WEBCAM_START"
cmd_ids[1114] = "COMMAND_ID_STDAPI_WEBCAM_STOP"
cmd_ids[1115] = "COMMAND_ID_STDAPI_AUDIO_MIC_START"
cmd_ids[1116] = "COMMAND_ID_STDAPI_AUDIO_MIC_STOP"
cmd_ids[1117] = "COMMAND_ID_STDAPI_AUDIO_MIC_LIST"
cmd_ids[1118] = "COMMAND_ID_STDAPI_SYS_PROCESS_SET_TERM_SIZE"
cmd_ids[1119] = "COMMAND_ID_STDAPI_SYS_PROCESS_MEMORY_SEARCH"
cmd_ids[2001] = "COMMAND_ID_PRIV_ELEVATE_GETSYSTEM"
cmd_ids[2002] = "COMMAND_ID_PRIV_FS_BLANK_DIRECTORY_MACE"
cmd_ids[2003] = "COMMAND_ID_PRIV_FS_BLANK_FILE_MACE"
cmd_ids[2004] = "COMMAND_ID_PRIV_FS_GET_FILE_MACE"
cmd_ids[2005] = "COMMAND_ID_PRIV_FS_SET_FILE_MACE"
cmd_ids[2006] = "COMMAND_ID_PRIV_FS_SET_FILE_MACE_FROM_FILE"
cmd_ids[2007] = "COMMAND_ID_PRIV_PASSWD_GET_SAM_HASHES"
cmd_ids[3001] = "COMMAND_ID_EXTAPI_ADSI_DOMAIN_QUERY"
cmd_ids[3002] = "COMMAND_ID_EXTAPI_CLIPBOARD_GET_DATA"
cmd_ids[3003] = "COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_DUMP"
cmd_ids[3004] = "COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_PAUSE"
cmd_ids[3005] = "COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_PURGE"
cmd_ids[3006] = "COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_RESUME"
cmd_ids[3007] = "COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_START"
cmd_ids[3008] = "COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_STOP"
cmd_ids[3009] = "COMMAND_ID_EXTAPI_CLIPBOARD_SET_DATA"
cmd_ids[3010] = "COMMAND_ID_EXTAPI_NTDS_PARSE"
cmd_ids[3011] = "COMMAND_ID_EXTAPI_PAGEANT_SEND_QUERY"
cmd_ids[3012] = "COMMAND_ID_EXTAPI_SERVICE_CONTROL"
cmd_ids[3013] = "COMMAND_ID_EXTAPI_SERVICE_ENUM"
cmd_ids[3014] = "COMMAND_ID_EXTAPI_SERVICE_QUERY"
cmd_ids[3015] = "COMMAND_ID_EXTAPI_WINDOW_ENUM"
cmd_ids[3016] = "COMMAND_ID_EXTAPI_WMI_QUERY"
cmd_ids[4001] = "COMMAND_ID_SNIFFER_CAPTURE_DUMP"
cmd_ids[4002] = "COMMAND_ID_SNIFFER_CAPTURE_DUMP_READ"
cmd_ids[4003] = "COMMAND_ID_SNIFFER_CAPTURE_RELEASE"
cmd_ids[4004] = "COMMAND_ID_SNIFFER_CAPTURE_START"
cmd_ids[4005] = "COMMAND_ID_SNIFFER_CAPTURE_STATS"
cmd_ids[4006] = "COMMAND_ID_SNIFFER_CAPTURE_STOP"
cmd_ids[4007] = "COMMAND_ID_SNIFFER_INTERFACES"
cmd_ids[7001] = "COMMAND_ID_WINPMEM_DUMP_RAM"
cmd_ids[8001] = "COMMAND_ID_KIWI_EXEC_CMD"
cmd_ids[10001] = "COMMAND_ID_UNHOOK_PE"
cmd_ids[11001] = "COMMAND_ID_ESPIA_IMAGE_GET_DEV_SCREEN"
cmd_ids[12001] = "COMMAND_ID_INCOGNITO_ADD_GROUP_USER"
cmd_ids[12002] = "COMMAND_ID_INCOGNITO_ADD_LOCALGROUP_USER"
cmd_ids[12003] = "COMMAND_ID_INCOGNITO_ADD_USER"
cmd_ids[12004] = "COMMAND_ID_INCOGNITO_IMPERSONATE_TOKEN"
cmd_ids[12005] = "COMMAND_ID_INCOGNITO_LIST_TOKENS"
cmd_ids[12006] = "COMMAND_ID_INCOGNITO_SNARF_HASHES"
cmd_ids[13001] = "COMMAND_ID_PYTHON_EXECUTE"
cmd_ids[13002] = "COMMAND_ID_PYTHON_RESET"
cmd_ids[14001] = "COMMAND_ID_POWERSHELL_ASSEMBLY_LOAD"
cmd_ids[14002] = "COMMAND_ID_POWERSHELL_EXECUTE"
cmd_ids[14003] = "COMMAND_ID_POWERSHELL_SESSION_REMOVE"
cmd_ids[14004] = "COMMAND_ID_POWERSHELL_SHELL"
cmd_ids[15001] = "COMMAND_ID_LANATTACKS_ADD_TFTP_FILE"
cmd_ids[15002] = "COMMAND_ID_LANATTACKS_DHCP_LOG"
cmd_ids[15003] = "COMMAND_ID_LANATTACKS_RESET_DHCP"
cmd_ids[15004] = "COMMAND_ID_LANATTACKS_RESET_TFTP"
cmd_ids[15005] = "COMMAND_ID_LANATTACKS_SET_DHCP_OPTION"
cmd_ids[15006] = "COMMAND_ID_LANATTACKS_START_DHCP"
cmd_ids[15007] = "COMMAND_ID_LANATTACKS_START_TFTP"
cmd_ids[15008] = "COMMAND_ID_LANATTACKS_STOP_DHCP"
cmd_ids[15009] = "COMMAND_ID_LANATTACKS_STOP_TFTP"
cmd_ids[16001] = "COMMAND_ID_PEINJECTOR_INJECT_SHELLCODE"
cmd_ids[17001] = "COMMAND_ID_MIMIKATZ_CUSTOM_COMMAND"